import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

interface Task {
  title: string;
  dueDate: string;
  status: string;
  id: number;
}

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>([]);

  const handleAddTask = () => {
    const newTask = {
      id: 1,
      title: "",
      dueDate: "",
      status: "pending",
    };

    setTasks([...tasks, newTask]);
  };

  return (
    <>
      <Head>
        <title>Doodle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Tasks</h1>
          <ul>
            {tasks.map((task) => (
              <li key={task.id}>
                <strong>{task.title}</strong>
                <p>{task.dueDate}</p>
                <p>{task.status}</p>
              </li>
            ))}
          </ul>
          <button onClick={handleAddTask}>Add Task</button>
        </div>
      </main>
    </>
  );
}
